# Generated by Django 4.2 on 2023-04-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='registerd',
        ),
    ]
