# Generated by Django 4.2 on 2023-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_poc_crt_company_poc_crt_subdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_poc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=50)),
                ('subdate', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=100)),
                ('registerd', models.CharField(max_length=7)),
                ('date', models.TextField()),
            ],
        ),
    ]
