# Generated by Django 4.2 on 2023-04-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_create_poc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='poc_crt',
        ),
    ]
