# Generated by Django 4.2 on 2023-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_delete_poc_crt'),
    ]

    operations = [
        migrations.CreateModel(
            name='comp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('last_date', models.CharField(max_length=10)),
                ('package', models.CharField(max_length=10)),
                ('branches', models.CharField(max_length=500)),
            ],
        ),
    ]
