# Generated by Django 4.2 on 2023-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_comp_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='details_comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=10)),
                ('package', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='comp_details',
        ),
    ]
