# Generated by Django 4.2 on 2023-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_details_comp_delete_comp_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_comp',
            name='name',
            field=models.CharField(default='apsolute', max_length=500),
            preserve_default=False,
        ),
    ]
