# Generated by Django 4.2 on 2023-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_details_comp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_poc',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100),
        ),
    ]
